services:
  frontend:
    build:
      target: runtime
    volumes: []
    environment:
      NGINX_PORT: "80"
    ports:
      - "${FRONTEND_PORT:-5173}:80"

  backend:
    build:
      target: runtime
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  worker:
    build:
      target: runtime

